### ISSUE TITLE
What's the purpose of ```assert(!options_.enable_spdklogging);``` in ycsbc::RocksDBClient::Load ?

### ISSUE THREAD

**Issue by seekstar** [SpanDB/SpanDB#5]
When the dbname is ```spandb```, ```options.enable_spdklogging``` is set to ```true``` in ycsb/src/test.cc, then the assertion fails:

```
SpanDB/ycsb/src/rocksdb_client.cc:15: void ycsbc::RocksDBClient::Load(): Assertion `!options_.enable_spdklogging' failed.
```

**Comment by cighao** [comment]
Thanks for your interest in SpanDB.
`Load()` is used to load the data to the DB. Now we only implement `RocksDB load()`. `SpanDB() load() `have not been implemented yet. So when calling `Load()`, it should be configured as `rocksdb` rather than `spandb`.  If you want to load data with SpanDB, you can implement the `SpanDB Load()`, referring to the `async_put()` interface.

**Comment by seekstar** [comment]
Thank you very much for the clarification.
